### ISSUE TITLE
Issue from Lab run March 5

### ISSUE THREAD

**Issue by azipory** [osevg/workshopper-content#7]
Hi All,

The following issues have encountered in this training I conducted March 5
(and I have another one tomorrow):

1. Chapter 12, Externalizing Application Configuration, does not load and Chapter 14 (ci/cd) does not
address the creation of a configmap for the live environment. Is this on purpose?
2. Application templates:
    Template URL https://raw.githubusercontent.com/openshift-roadshow/mlbparks//ose3/application-template-wildfly.json is incorrect.
3. CI/CD pipline is loaded with the wrong urls in the Test Dev stage. (e.g.:http://nationalparks.explore-05.svc.cluster.local:8080 instead of, for example, http://nationalparks-explore-05.cloudapps.<customer-name>.openshift3roadshow.com/ws/data/load)
Thanks, Amir
(azipory@redhat.com)

**Comment by thoraxe** [comment]
These should all be fixed at this point. Most were configuration/runtime issues.

**Comment by azipory** [comment]
Issue no. 3 from above still exists.
pipeline loaded with incorrect urls at the Test Dev stage.

**Comment by thoraxe** [comment]
Hi Amir,
I'm not sure I can agree with #3 -- I just conducted an experiment wiht the content and while the URL might be what you say it is, it works fine. I don't have any errors or anything? What problem were you seeing with this URL?

**Comment by jorgemoralespou** [comment]
Content has been changed since then. I can't reproduce any of the issues.
I think the issue might be related to how ansible creates loads the template.

Will close, and open a new issue if you find the issue again.
